### ISSUE TITLE
Tune samples to notes

### ISSUE THREAD

**Issue by ucodelukas** [monocasual/giada#390] opened 2020-08-13 18:02 UTC
ability to use a sample with different pitch but the pitch can be set by note :O

**Comment by tomek-szczesny** [comment] 2020-08-14 10:52
Sounds pretty much like me recent feature request #362 :)

**Comment by ucodelukas** [comment] 2020-12-21 06:03
Hey, i just thought I can already change the pitch of a sample but I would like to have a stepped note instead

**Comment by gvnnz** [comment] 2021-01-10 09:02
Thanks @ucodelukas for the input. I'm closing this as duplicate of #362 .

**Closed by gvnnz** 2021-01-10 09:02 UTC
