### ISSUE TITLE
Building 0.15.3 > Build problem with FLTK 1.3.5 / Missing 'include'

### ISSUE THREAD

**Issue by moonshaadow** [monocasual/giada#246] opened 2019-03-20 14:40 UTC
Hello!
Trying to build the Giada 0.15.3 version ( website version) with gcc 5.x (on Ubuntu 16.04 with xfce)
Not working with FLTK 1.3.5 ( many missing include <FL/Fl_xxx> ), but it could be a FLTK building problem, as it could be fix using 1.3.0 .

Also encountered the 'missing include' part of #229, but with gcc 5.x . The fix proposed works well for me.

**Comment by monocasual** [comment] 2019-03-23 08:59
Hi! This is just a wild guess, but I thing FLTK 1.3.5 is currently not supported in Giada. You could try with 0.15.4 released yesterday to see if the error persists. Anyway we will upgrade FLTK to 1.3.5 in the next release, so it's just a matter of time.

**Comment by RarogCmex** [comment] 2019-08-13 14:03
Release 0.15.4 and fltk 1.3.3, issue persist

**Comment by monocasual** [comment] 2019-08-15 07:46
@RarogCmex are you able to build a different FLTK-based app, e.g. their bundled examples?

**Comment by RarogCmex** [comment] 2019-08-15 07:56
> are you able to build a different FLTK-based app, e.g. their bundled examples?
I use Gentoo linux so yes, It's built.

**Comment by RarogCmex** [comment] 2019-08-15 08:00
At least I builded yoshimi and zynaddsubfx which fltk-based

**Comment by monocasual** [comment] 2019-08-19 15:13
I'll take a look at how those apps include FLTK in their codebase, maybe there's a best practice we are missing right now. Stay tuned...

**Comment by RarogCmex** [comment] 2019-12-14 15:39
Giada 0.16.0, issue still present 
configure: error: library 'fltk' not found!

[build.log](https://github.com/monocasual/giada/files/3963983/build.log)

**Comment by RarogCmex** [comment] 2019-12-14 15:40
=================================================================
                        Package Settings
=================================================================

x11-libs/fltk-1.3.5-r4::gentoo was built with the following:
USE="cairo opengl threads xft xinerama -debug -doc -examples -games -static-libs" ABI_X86="32 (64) (-x32)"

**Comment by monocasual** [comment] 2019-12-14 15:57
@RarogCmex so it looks like a configuration problem in Giada. Currently the script checks the availability of `FL/Fl.H` header. Does such path exist in your system?

**Comment by RarogCmex** [comment] 2019-12-16 09:36
Ok, i found two ones:
/usr/include/fltk/FL/Fl.H
/usr/include/ntk/FL/Fl.H
And this is cause bug, because giada search for /usr/include/FL/Fl.H . May be giada should also check presence in /usr/include/fltk/FL/Fl.H

**Comment by monocasual** [comment] 2019-12-23 21:17
Commit 90f643b390c755f9a4bc642230a90a69d840cc1c on `fltk-fix` branch is an attempt to fix this. @RarogCmex does it work for you?

**Comment by RarogCmex** [comment] 2019-12-26 11:48
> does it work for you?
It seems no...
[build.log](https://github.com/monocasual/giada/files/4002418/build.log)
[fix-fltk.patch.zip](https://github.com/monocasual/giada/files/4002421/fix-fltk.patch.zip)

As you see in build log patch has been applied but has had no succesfull result.

**Comment by monocasual** [comment] 2020-01-06 17:23
This is weird and unfortunately not reproducible here. I'm marking the issue as 'help wanted' in case someone has better Autotool skills (until #153 takes over!).

**Comment by monocasual** [comment] 2020-09-27 10:23
#153 implemented, issue should be fixed. Please reopen if necessary.

**Closed by monocasual** 2020-09-27 10:23 UTC
Labels: bug, help wanted
