### ISSUE TITLE
The Sample Editor sometimes freezes Giada

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#548] opened 2022-01-11 22:45 UTC
The issue seems to be caused by the Swapper being stuck on the `swap` method. It happens when the sample is playing in the project and the pitch is changed from the Sample Editor.

I could reproduce it only with very short samples.

**Comment by gvnnz** [comment] 2023-08-27 21:10
Can't reproduce this anymore. Closing.

**Closed by gvnnz** 2023-08-27 21:10 UTC
Labels: bug
