### ISSUE TITLE
0.17.2  is freezing at any step (with JACK)

### ISSUE THREAD

**Issue by moonshaadow** [monocasual/giada#457] opened 2021-04-04 16:20 UTC
**Environment**
- OS: ubuntu 18.4
- Giada version: 0.17.2 AppImage

**Describe the bug**
Gui is freezing when adding a track, when quitting the app, when open menu.
Starting with command line, there is no information about the error.

**To Reproduce**
1. Start Giada
2. Quit the app
3. Confirm

**Expected behavior**
a non-freezing app :)

**Comment by gvnnz** [comment] 2021-04-11 09:51
Can't reproduce on a freshly installed Ubuntu 18.04 (VirtualBox).

**Comment by moonshaadow** [comment] 2021-04-12 15:03
Sorry this is Ubuntu Studio 18.04 (xfce, low-latency kernel, JACK2).
More info, if this is relevant :
```
Python version: 3.6.9
Qt version:     5.9.5
PyQt version:   5.10.1

jackdmp version 1.9.17

kernel version : 4.15.0-140-lowlatency (#144-Ubuntu SMP PREEMPT Fri Mar 19 15:15:04 UTC 2021)

Xorg version : 1.19.6 (30 November 2020  08:01:56PM)

graphic card : Radeon HD 7470

```

**Comment by moonshaadow** [comment] 2021-04-12 15:17
Maybe more relevant : 

The first launch seems good, then the app seems to freeze after the second lauch if and only if I choose Jack as driver.


```
~$ '/home/studio/Bureau/Giada-0.17.2-x86_64.AppImage'
[init] Giada 0.17.2
[init] Build date: Mar 28 2021
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.3.4
[init]   RtAudio - 5.1.0
[init]   RtMidi - 3.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.9.1
[init]   JUCE - 6.0.7
[KA] Compiled RtAudio APIs: 3
  JACK
  PulseAudio
  ALSA
[midiMapConf::init] scanning midimaps directory '/home/studio/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!

```

**Comment by moonshaadow** [comment] 2021-04-20 15:37
Building from sources, I can confirm the problem is always here, and is related to JACK.
The app seems good with ALSA or pulseaudio.

_jackd2 version : 1.9.18_

_______
_I don't know what is the statement here regarding JACK and Linux audio, but here my point of view :_ 
   - Using ALSA directly is OK, but it prevents to use any other audio apps in the same time ; 
   - pulseaudio is not suitable for audio production, and it is programmed to disappear in the very next years ; 
   - JACK is multi-platforms and allows endless modularity in connections. It's probably such a niche on Windows and macOS, but it's the leading for linux audio production.

**Comment by gvnnz** [comment] 2021-06-27 09:37
@moonshaadow several JACK-related improvements have been added since April in the current master branch: could you please try again and see if the issue persists in your setup? Thanks!

**Comment by gvnnz** [comment] 2021-12-11 08:35
No feedback since June, closing.

**Closed by gvnnz** 2021-12-11 08:35 UTC
Labels: To be confirmed
