### ISSUE TITLE
Giada freezes on exit when output is Jack on a Pipewire based system

### ISSUE THREAD

**Issue by Kirtai** [monocasual/giada#597] opened 2022-07-22 17:20 UTC
**Environment**
- OS: EndeavorOs
- Giada version: 0.22.0

**Describe the bug**
If I set Jack as the output on a system running Pipewire, Giada will hang on exit and produce a stream of the following errors
```
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
[KA] RtAudio error 1: RtApiJack::callbackEvent(): the JACK buffer size has changed ... cannot process!
```
**To Reproduce**
1. Install Giada on an up to date distro like Arch or EndeavorOS
2. Set output to Jack and enable debugging messages.
3. Save and exit.
4. Start Giada again.
5. You will now see the error message spam and Giada will freeze when told to quit.
6. The only way I have found to prevent this is to completely remove the configuration file before restarting.

**Expected behavior**
Giada should exit without freezing and run without Jack error messages.

**Comment by gvnnz** [comment] 2022-07-25 08:45
Hey @Kirtai , thanks for reporting. We are using https://github.com/thestk/rtaudio as a backend which currently doesn't support Pipewire. There is a proposal for Pipewire implementation here: https://github.com/thestk/rtaudio/issues/324.

**Comment by macramole** [comment] 2022-08-30 03:24
I found a workaround to this problem (at least for [AudioStellar](https://gitlab.com/ayrsd/audiostellar))
1. Copy jack.conf from /usr/share/pipewire to ~/.config/pipewire
2. Edit the file adding node.force-quantum option to jack.properties

In my configuration I'm using node.latency = 512/44100 and node.force-quantum = 512 . I guess latency and force-quantum should match but I'm not sure.

**Comment by ericek111** [comment] 2022-09-17 15:27
This should also work until the next reboot:
```
pw-metadata -n settings 0 clock.force-quantum 1024
```

**Comment by runiq** [comment] 2023-09-29 16:00
> Hey @Kirtai , thanks for reporting. We are using https://github.com/thestk/rtaudio as a backend which currently doesn't support Pipewire. There is a proposal for Pipewire implementation here: [thestk/rtaudio#324](https://github.com/thestk/rtaudio/issues/324).

Unfortunately, that link 404s. I couldn't find anything regarting rtaudio and Pipewire support, but… shouldn't this "just work" as long as Pipewire's JACK implementation is compliant?

**Comment by gvnnz** [comment] 2023-12-21 18:38
Tested latest version (0.26.1) with JACK + Pipewire on Debian, can't reproduce this. Closing.

**Closed by gvnnz** 2023-12-21 18:38 UTC
Labels: bug, enhancement
