### ISSUE TITLE
v0.17.1 segfaults after second config

### ISSUE THREAD

**Issue by dromer** [monocasual/giada#448] opened 2021-02-11 16:05 UTC
**Environment**
- OS: Debian Buster
- Giada version: v0.17.1

Giada segfaults after going to `config` for the second time.

**To Reproduce**
1. Go to `config`
2. Save config
3. Go to `config` again
4. Segfault

**Expected behavior**
Simply see the current config

**Comment by dromer** [comment] 2021-02-11 16:06
If I save the configuration, then quit Giada, restart, and try again it does work.

**Comment by tomek-szczesny** [comment] 2021-02-11 18:14
Could you try running Giada in terminal and capture possible errors it returns?

**Comment by dromer** [comment] 2021-02-11 18:35
Where does Giada store the config? it is not in `~/.config/`
(I'll have to remove it in order to reproduce, I think)

**Comment by tomek-szczesny** [comment] 2021-02-11 18:44
It's probably in ~/.giada/.
Is there a possibility you had an old config file from one of the previous versions?

**Comment by dromer** [comment] 2021-02-11 18:54
Ok, I deleted the folder and restarted.
Same result:
```
dreamer@auditorium:~/Downloads/_bin$ ./Giada-0.17.1-x86_64.AppImage 
[init] Giada 0.17.1
[init] Build date: Jan 31 2021
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.3.4
[init]   RtAudio - 5.1.0
[init]   RtMidi - 3.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.9.1
[init]   JUCE - 6.0.4
[KA] Compiled RtAudio APIs: 3
  JACK
  PulseAudio
  ALSA
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '/home/dreamer/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
Segmentation fault
```

**Comment by tomek-szczesny** [comment] 2021-02-11 19:27
Okay then, too bad it doesn't say anything specific. Perhaps gdb will reveal the secrets of this behavior.
I'm not surprised, there used to be some odd behaviors with config dialog in the past.

**Comment by dromer** [comment] 2021-02-11 21:16
With gdb:

```
dreamer@auditorium:~/Downloads/_bin$ gdb ./Giada-0.17.1-x86_64.AppImage 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Giada-0.17.1-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/dreamer/Downloads/_bin/Giada-0.17.1-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 21855]
process 21851 is executing new program: /tmp/.mount_Giada-ZYM33c/usr/bin/giada
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[init] Giada 0.17.1
[init] Build date: Jan 31 2021
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.3.4
[init]   RtAudio - 5.1.0
[init]   RtMidi - 3.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.9.1
[init]   JUCE - 6.0.4
[KA] Compiled RtAudio APIs: 3
  JACK
  PulseAudio
  ALSA
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '/home/dreamer/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!

Program received signal SIGSEGV, Segmentation fault.
0x000055555565a295 in ?? ()
(gdb) bt
#0  0x000055555565a295 in ?? ()
#1  0x00005555556bef14 in ?? ()
#2  0x00005555556c0070 in ?? ()
#3  0x000055555569771b in ?? ()
#4  0x00005555556b3c05 in ?? ()
#5  0x00007ffff7b0c761 in Fl_Widget::do_callback(Fl_Widget*, void*) ()
   from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#6  0x00007ffff7abd0da in Fl_Button::handle(int) () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#7  0x00007ffff7ab50cd in ?? () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#8  0x00007ffff7ab6f83 in Fl::handle_(int, Fl_Window*) ()
   from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#9  0x00007ffff7b13712 in fl_handle(_XEvent const&) () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#10 0x00007ffff7b14f92 in ?? () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#11 0x00007ffff7b152b8 in fl_wait(double) () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#12 0x00007ffff7ab6970 in Fl::wait(double) () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#13 0x00007ffff7ab69ed in Fl::run() () from /tmp/.mount_Giada-ZYM33c/usr/bin/../lib/libfltk.so.1.3
#14 0x0000555555601f3b in main ()
```


I find it odd that when I press `save` it doesn't actually save anything. You have to close the program before it creates `~/.giada` and saves the config.

**Comment by tomek-szczesny** [comment] 2021-02-12 07:21
Thanks for your effort!
Hm, I didn't expect that kind of output. I usually do gdb sessions on whatever I compiled myself, hence the symbols are available. Anyway, yeah, the save button callback does something wrong indeed.
Unfortunately I can't reproduce your problem because I do not have x86 machine atm. I may try compiling the recent release for ARM later this week and see if the same problem is present.

I think that saving config at program exit is a status quo, that was done for some reason and just behaved well so far. Perhaps the reason is that there are settings indirectly modified by the user, such as window sizes and positions, that ought to be saved as well. If this is the case, I'm guessing that saving config additionally at closing config window would do the trick.

**Comment by dromer** [comment] 2021-02-12 08:04
It would at least be consistent to save when the user presses the save button. And then maybe additionally when closing the program ;)

**Comment by gvnnz** [comment] 2021-07-23 15:00
Audio config process has been rewritten from scratch few versions ago. Please reopen if the segfaults persist.

**Closed by gvnnz** 2021-07-23 15:00 UTC
