### ISSUE TITLE
High delay between microphone and the metronome 

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#304] opened 2020-01-25 16:43 UTC
Some users on YouTube (in the comment section of [this video tutorial](https://www.youtube.com/watch?v=L66CA1Umk4w)) report a latency problem during audio recording:

> There is an annoying delay between my microphone and the metronome after I record a sample. Any way to fix this?

And:

> I think the program has a serious latency problem. I have experienced the same problem at every buffer size with a high performance PC and excellent interface/mixer setup.

**Comment by tomek-szczesny** [comment] 2020-07-25 14:33
I played around with Giada on a Windows machine during coffee break at work, and indeed it has a crazy delay when recording from the mic. No such issues on Linux and Jack though.

**Comment by BRFNGRNBWS** [comment] 2020-10-09 04:39
Can confirm latency using pulseaudio on opensuse. Other programs, such as reaper or audacity, don't have any latency problems when using pulse

**Comment by monocasual** [comment] 2020-10-16 16:52
I too have experienced this problem. @tomek-szczesny and @BRFNGRNBWS, try the following: when the latency is crazy, open the Configuration window, change the buffer size (any value is good), close and restart Giada. The latency should go back to normal. I'm still not sure where the issue comes from, I suspect somewhere in RtAudio on Linux and the PulseAudio API.

**Comment by AJRepo** [comment] 2021-11-14 23:26
I too have had this problem on a Ubuntu 20.04 system with hardware  CPU="Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz" (reporting 6  cores & 12 threads), mem=64MiB and using Pulseaudio for the input/output/system in config. I tried it with setting buffer size from 1024 (default) to 2048 and 4096. Also tried setting "resampling" to "Zero Order Hold (Fast)" without being able to solve the latency issue. Not sure what else to try.

**Comment by gvnnz** [comment] 2021-11-15 08:26
@AJRepo thanks for reporting. Are you able to reproduce this or is it just random?

**Comment by AJRepo** [comment] 2021-11-15 14:15
I am able to reproduce this.

**Comment by gvnnz** [comment] 2021-11-19 18:07
RtAudio has been updated to version 5.2.0/6.0.0beta today (a71467fbf21ed99ab711761d982e4b019c2fd4bf), things might have improved now, at least in the development version.

**Comment by gvnnz** [comment] 2023-06-04 15:12
Can't reproduce this one with new RtAudio 6.x, closing.

**Closed by gvnnz** 2023-06-04 15:12 UTC
Labels: bug, To be confirmed
