### ISSUE TITLE
Build fails with gcc 12

### ISSUE THREAD

**Issue by lgbaldoni** [monocasual/giada#586] opened 2022-05-24 04:41 UTC
**Environment**
- OS: openSUSE Tumbleweed
- Giada version: 0.21.0+git.20220521.ce35a252

**Describe the bug**
Build fails, see log snippet below.

**To Reproduce**
1. `/usr/bin/cmake /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/giada -DCMAKE_BUILD_TYPE=Release -DWITH_VST3=ON`
2. `make`

**Expected behavior**
No error

**Screenshots**
```
make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/build'
[  0%] Building CXX object CMakeFiles/giada.dir/src/main.cpp.o
/usr/bin/g++ -DFMT_LOCALE -DFMT_SHARED -DJUCE_DEBUG=0 -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_MODAL_LOOPS_PERMITTED=1 -DJUCE_MODULE_AVAILABLE_juce_gui_basics=1 -DJUCE_PLUGINHOST_AU=0 -DJUCE_PLUGINHOST_VST3=1 -DJUCE_STANDALONE_APPLICATION=1 -DJUCE_USE_CURL=0 -DJUCE_WEB_BROWSER=0 -DNDEBUG -DWITH_AUDIO_JACK -DWITH_VST -DWITH_VST3 -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__ -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252 -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/vst3sdk -I/usr/include/freetype2 -isystem /usr/include/rtmidi -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O3 -DNDEBUG -Wall -Wextra -Wpedantic -pthread -D__UNIX_JACK__ -D__LINUX_ALSA__ -MD -MT CMakeFiles/giada.dir/src/main.cpp.o -MF CMakeFiles/giada.dir/src/main.cpp.o.d -o CMakeFiles/giada.dir/src/main.cpp.o -c /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/main.cpp
In file included from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_gui_basics/juce_gui_basics.h:270,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_audio_processors/juce_audio_processors.h:57,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce-config.h:6,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/core/channels/channel.h:32,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/core/channels/channelManager.h:30,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/core/engine.h:32,
                 from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/main.cpp:27:
/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h: In member function 'void juce::ComponentPeer::setAppStyle(Style)':
/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h:442:18: error: 'exchange' is not a member of 'std'
  442 |         if (std::exchange (style, s) != style)
      |                  ^~~~~~~~
```

**Additional context**
This happens whilst building a rpm package on openSUSE OBS.

**Comment by edogawa23** [comment] 2022-05-24 10:22
Being co-maintainer of the rpm package in OBS, I wanted to add that Tumbleweed recently switched to gcc-12 as default compiler, and explicitely injecting -std=c++-17 to CXXFLAGS doesn't help with it either:
(directly pasting the log from building a slightly older github checkout, apparently markdowning this as Code removes newlines)

[  127s] /usr/bin/g++ -DJUCE_DEBUG=0 -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_MODAL_LOOPS_PERMITTED=1 -DJUCE_MODULE_AVAILABLE_juce_gui_basics=1 -DJUCE_PLUGINHOST_AU=0 -DJUCE_PLUGINHOST_VST3=1 -DJUCE_STANDALONE_APPLICATION=1 -DJUCE_USE_CURL=0 -DJUCE_WEB_BROWSER=0 -DNDEBUG -DWITH_AUDIO_JACK -DWITH_VST -DWITH_VST3 -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__ -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce/modules -I/home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/vst3sdk -I/usr/include/freetype2 -isystem /usr/include/rtmidi -std=c++17 -DNDEBUG -O3 -DNDEBUG -Wall -Wextra -Wpedantic -pthread -D__UNIX_JACK__ -D__LINUX_ALSA__ -MD -MT CMakeFiles/giada.dir/src/main.cpp.o -MF CMakeFiles/giada.dir/src/main.cpp.o.d -o CMakeFiles/giada.dir/src/main.cpp.o -c /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/main.cpp
[  127s] In file included from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce/modules/juce_gui_basics/juce_gui_basics.h:270,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce/modules/juce_audio_processors/juce_audio_processors.h:57,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce-config.h:6,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/core/channels/channel.h:32,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/core/channels/channelManager.h:30,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/core/engine.h:32,
[  127s]                  from /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/main.cpp:27:
[  127s] /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h: In member function 'void juce::ComponentPeer::setAppStyle(Style)':
[  127s] /home/abuild/rpmbuild/BUILD/giada-0.21.0+git.20220312.9f123ccf/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h:442:18: error: 'exchange' is not a member of 'std'
[  127s]   442 |         if (std::exchange (style, s) != style)
[  127s]       |                  ^~~~~~~~
[  127s] make[2]: *** [CMakeFiles/giada.dir/build.make:79: CMakeFiles/giada.dir/src/main.cpp.o] Error 1

**Comment by edogawa23** [comment] 2022-05-24 11:08
In another test, I forced the rpm package to use gcc11-c++ instead of default g++, and that made the error vanish, as was to be expected. not a durable solution, but a workaround for now.

**Comment by gvnnz** [comment] 2022-05-26 17:04
Hi @lgbaldoni @edogawa23 , thanks for reporting. [`std::exchange`](https://en.cppreference.com/w/cpp/utility/exchange) was introduced in C++14: maybe the compiler is set to C++11 mode? Our CMakeLists.txt is instructed to generate the proper flags for C++17 (see [here](https://github.com/monocasual/giada/blob/master/CMakeLists.txt#L217)), not sure why it doesn't work correctly.

**Comment by edogawa23** [comment] 2022-05-27 11:16
I don't know either, but this setting doesn't seem to make it through to the actual g++ option list when compiling.
I'm a bit clueless, not too familiar with cmake. I've tried to read up on cmake and language standards but i feel more confused than before... anyways the workaround is in place, got accepted as a hotfix for the distro package, and will probably work as long as gcc-11 is around for Tumbleweed.

**Comment by lgbaldoni** [comment] 2022-05-27 11:29
@gvnnz 
> maybe the compiler is set to C++11 mode? 

You can see the full g++ command line in the log snippet above. I tried forcing C++14/C++17/C++20 with no improvement.

@edogawa23 
> the workaround is in place, got accepted as a hotfix for the distro package, and will probably work as long as gcc-11 is around for Tumbleweed

Which you can't count on for long. Perhaps this might be deserving of a test with clang.

**Comment by edogawa23** [comment] 2022-05-28 07:50
I've branched giada to my [home project](https://build.opensuse.org/package/show/home:edogawa/giada), reverted the workaround to use gcc-11, so one can see the original breakage(click the "Failed" button to see the logs); To me it seems the existing call for c++17 in CMakeLists.txt has no effect whatsoever after the cmake run. I'll happily try any proposed soluton and look to find an alternative way of forcing the needed language standard when time permits.

**Comment by gvnnz** [comment] 2022-05-28 08:57
> To me it seems the existing call for c++17 in CMakeLists.txt has no effect whatsoever after the cmake run

This is weird. I just checked the files generated by CMake here (version 3.18.4), especially `[build-dir]/CMakeFiles/giada.dir/flags.make`. It contains the following:

`CXX_FLAGS = -g -Wall -Wextra -Wpedantic -pthread -std=gnu++17`

@edogawa23 can you please check the content of that file on your system?

**Comment by lgbaldoni** [comment] 2022-05-28 19:11
This fixes it for me, but I can't very well make a PR for a dependency, can I?

```
Index: giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h
===================================================================
--- giada-0.21.0+git.20220521.ce35a252.orig/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h
+++ giada-0.21.0+git.20220521.ce35a252/src/deps/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.h
@@ -23,6 +23,8 @@
   ==============================================================================
 */
 
+#include <utility>
+
 namespace juce
 {

```

So @gvnnz if you can't find a better place to add the include, we'll just keep this as local patch.

**Comment by edogawa23** [comment] 2022-05-28 19:14
I checked and it's not there:
`CXX_FLAGS = -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG -O3 -DNDEBUG -Wall -Wextra -Wpedantic -pthread -D__UNIX_JACK__ -D__LINUX_ALSA__`

**Comment by edogawa23** [comment] 2022-05-29 08:21
@gvnnz No -std=gnu++17 isn't present here in `[build-dir]/CMakeFiles/giada.dir/flags.make`
I'm trying several things on this route, without success so far, it seems cmake 3.23.1 detects gcc-12.1 and a higher default language spec correctly and decides to drop the -std= option altogether (as indicated in cmake docs).
Trying a different method - setting 
`set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)`
in CMakeLists.txt, same result.

**Comment by lgbaldoni** [comment] 2022-05-29 08:51
@edogawa23 perhaps something is lost in cut and paste (tabs or line endings), please see [home:alois:branches:multimedia:apps/giada](https://build.opensuse.org/package/show/home:alois:branches:multimedia:apps/giada).

Unfortunately other things are broken there.

**Comment by edogawa23** [comment] 2022-05-29 09:48
@lgbaldoni oh indeed, I overlooked the indicating error message... your patch has CRLF line endings. I copied your file to my local osc working copy and that works.

**Comment by edogawa23** [comment] 2022-05-29 10:37
This builds now in my local checkout of current github.

I'll merge @lgbaldoni's changes into my branch, run the source service to update github checkout to current, add the new build dependency pkgconfig(fmt), and submit that up > multimedia:proaudio > multimedia:apps > Factory if noone objects.

**Comment by edogawa23** [comment] 2022-06-02 15:34
@gvnnz would you apply this patch?

Our package including @lgbaldoni's fix got [accepted](https://build.opensuse.org/request/show/979798), so I'd think this issue can be set to solved.

**Comment by gvnnz** [comment] 2022-06-06 15:32
@edogawa23 unfortunately we can't apply @lgbaldoni patch ourselves, since it touches a 3rd-party dependency. I would suggest to open a PR in [JUCE repo](https://github.com/juce-framework/JUCE) instead. 

Anyway I'll keep this issue open until we will upgrade to GCC 12 (soon, hopefully).

**Comment by edogawa23** [comment] 2022-06-06 17:23
Ah of course, i forgot what file the patch targets. Fine with me!

**Comment by gvnnz** [comment] 2023-12-17 13:59
Can't reproduce this on GCC 12 with latest master (fcb75af98a0b5cee092291f49f71fed8e0eff8be), closing. @lgbaldoni feel free to reopen otherwise.

**Closed by gvnnz** 2023-12-17 13:59 UTC
Labels: bug, To be confirmed
