### ISSUE TITLE
When setting start and end points in sample edit, it crashes

### ISSUE THREAD

**Issue by muziker** [monocasual/giada#307] opened 2020-02-01 04:18 UTC
Using v0.16.1-3-g8d831ad4. When setting start and end points in sample edit, the application crashes

**Comment by muziker** [comment] 2020-02-01 04:41
this happens for v0.16.0 as well

**Comment by muziker** [comment] 2020-02-01 04:48
This also happens for the goblins release

**Comment by monocasual** [comment] 2020-02-02 09:06
Thanks for reporting! Which OS are you using? Also, what is the sample rate of your sample and your project?

**Comment by muziker** [comment] 2020-02-02 10:13
The sample rate of the os should be 48khz. The sample is sampled from the incoming audio stream, so it is the same

**Comment by monocasual** [comment] 2020-02-02 10:50
I'm unable to reproduce the crash here (currently on Linux, Debian stable). Could you please attach some debug output/backtrace?

**Comment by muziker** [comment] 2020-02-02 11:52
Is there a verbose debug mode somewhere? Right now it's just lines of jack output and a segfault

**Comment by muziker** [comment] 2020-02-02 11:55
found the debug flag

**Comment by muziker** [comment] 2020-02-02 12:08
Right here's a salient output from an assert statement

giada: ./src/core/model/model.h:155: auto giada::m::model::getIter(L&, giada::ID) [with L = giada::m::RCUList<giada::m::Wave>; giada::ID = int]: Assertion `it != list.end()' failed.

**Comment by muziker** [comment] 2020-02-11 06:00
I've run the test suite on giada, and it passes, but setting sample start and end from the sample editor right click menu causes giada to crash

**Comment by monocasual** [comment] 2020-02-11 09:15
According to the assert above it looks like the editor is trying to access the wrong sample object. @muziker could you please list here the steps to reproduce the problem?

**Comment by muziker** [comment] 2020-02-11 11:01
Ok ...
1. arm a track for recording an audio sample
2. record a sample from the input source
3. open the sample editor
4. drag and highlight a space in the sample editor
5. right click and select "set start/end point" 
6. experience the crash

**Comment by gvnnz** [comment] 2021-07-23 14:46
Very old bug from old architecture. Closing this as it should have been fixed along the way. @muziker please reopen it otherwise.

**Closed by gvnnz** 2021-07-23 14:46 UTC
Labels: To be confirmed, bug
