### ISSUE TITLE
[macOS] config not saved when exiting

### ISSUE THREAD

**Issue by aduermael** [monocasual/giada#240] opened 2019-02-10 10:43 UTC
When I try to restart Giada for config to be updated, it crashes and the config is never written:

<img width="545" alt="screen shot 2019-02-10 at 11 44 44 am" src="https://user-images.githubusercontent.com/6775074/52532687-5c7b3c00-2d29-11e9-9750-61aebfe977ca.png">

It always happens on `File > Quit Giara`. 
I always see this log then when I launch the app: `[init] Can't read configuration file! Using default values`. `giada.conf` is never written.

console logs: 

```
$ /Applications/giada.app/Contents/MacOS/giada_osx ; exit;
[init] Giada 0.15.3 - Sun Feb 10 11:42:56 2019
[conf::read] unable to read configuration file! Error on line -1: unable to open /Users/*****/Library/Application Support/Giada/giada.conf: No such file or directory
[init] Can't read configuration file! Using default values
[init] scanning midimaps directory...
[init] unable to scan midimaps directory!
libc++abi.dylib: terminating
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]
```

**Comment by monocasual** [comment] 2019-03-23 09:05
Thanks for reporting. I noticed random crashes in the past with some VST plug-ins not being unloaded correctly on shutdown. Are you using any VSTs in your setup/project/patch?

**Comment by aduermael** [comment] 2019-03-24 18:27
No, I did not use any plugins. This happened on a fresh install.

**Comment by maximilianotaverna** [comment] 2019-04-26 10:49
same here on mojave 10.14.4 brand new macbook air

**Comment by monocasual** [comment] 2020-06-20 07:15
Duplicate of #157 .

**Closed by monocasual** 2020-06-20 07:15 UTC
Labels: To be confirmed, bug
