### ISSUE TITLE
"One-shot press" channel mode doesn't work if triggered via mouse

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#262] opened 2019-10-31 19:53 UTC

**Comment by monocasual** [comment] 2019-11-01 17:50
Partially fixed in c45da37a6e8bff9adb56150b8117b4baad18c1e7. The issue is still present if the channel is triggered with the mouse.

**Comment by monocasual** [comment] 2020-02-02 11:30
Depends on #277 .

**Comment by monocasual** [comment] 2020-04-30 22:06
Fixed in development version, `non-virtual-channels` branch.

**Closed** 2020-05-08 19:29 UTC
Labels: bug
