### ISSUE TITLE
[Windows] No icon on executable giada_win.exe

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#317] opened 2020-03-08 11:29 UTC
> This is not exaclty a bug, but I noticed the file giada_win.exe doesn't have an icon, so Windows shows up its default icon. No attractive at all. I really like Giada logo and I think it would make a great icon for the exe. Plus, it will look nice on any start up painel.

https://giadamusic.com/forum/viewtopic.php?f=2&t=1566&p=2532#p2532

**Comment by gvnnz** [comment] 2023-08-26 14:25
Can't reproduce on Windows 11, closing.

**Closed by gvnnz** 2023-08-26 14:25 UTC
Labels: bug, enhancement
