### ISSUE TITLE
[macOS] Crash when macOS attempts to close a fullscreen tab

### ISSUE THREAD

**Issue by rnkn** [monocasual/giada#129] opened 2017-04-11 09:11 UTC
macOS recently introduced the notion of tabs to all apps (regardless of whether those apps required tabs). This causes a crash in giada in certain reproducible circumstances.

To reproduce:

1. open macOS System Preferences
1. select Dock > Prefer tabs when opening documents > Always / Full Screen Only
1. open giada
1. enter fullscreen by clicking the green button in window header
1. click any **FX** button
1. click **-- add new plugin --**
1. click **Add** or **Cancel**

This will trigger a crash. An easy workaround for the user is just to set the prefer tabs preference to Manual, but avoiding a crash would be best 😎

n.b. I seem to be able to trigger a crash in similar circumstances when the giada window is *not* fullscreen and I open or close the new plugin tab, but this is inconsistent.

Thanks 🙏

**Comment by monocasual** [comment] 2017-04-19 19:26
Does it happen only when adding/removing a plugin through the FX list window? Could you provide a backtrace output (GDB or similar)? Unfortunately we are not able to reproduce it right now: we are stuck on OS X 10.5 for building reasons.

**Comment by rnkn** [comment] 2019-06-01 10:38
Sorry for forgetting about this! I'm going through my old issues and thought I'd test this again. I cannot now reproduce on macOS 10.14.5 (18F132). Maybe it was an Apple bug that they've fixed?

**Comment by monocasual** [comment] 2019-06-01 13:51
@rnkn could be! I'm happily closing this as auto-resolved :sunglasses:

**Closed by monocasual** 2019-06-01 13:51 UTC
Labels: To be confirmed, bug
