### ISSUE TITLE
BPM not changing via Jack

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#331] opened 2020-04-25 20:21 UTC
Source: https://www.giadamusic.com/forum/viewtopic.php?f=2&t=1570

>  I change the tempo using Carla [with Jack] but the tempo number in Giada doesn't change and the beat counter keeps going at the same speed.

**Comment by terencode** [comment] 2020-04-25 20:33
Isn't this a duplicate of #238 ?

**Comment by tblrchstr** [comment] 2020-04-28 08:08
@terencode the title is a bit misleading, my bad. The problem here is that changing BPM in a Jack client (Carla, in the example) doesn't propagate back to Giada.

**Comment by monocasual** [comment] 2020-06-06 10:32
Fixed in development branch `non-virtual-channels`.

**Closed by monocasual** 2020-06-06 10:32 UTC
Labels: bug
