### ISSUE TITLE
segmentation fault when using jack

### ISSUE THREAD

**Issue by sezanzeb** [monocasual/giada#368] opened 2020-07-25 10:19 UTC
Duplicate of https://github.com/monocasual/giada/issues/360. That one has been closed because there is some sort of workaround. But I guess the proper fix would be if it doesn't crash in the first place..., even if the workaround described there works.

After launching giada, setting the "System" to jack in config and restarting, it crashes with:

```
[init] Giada 0.16.4
[init] Build date: Jul 25 2020
[init] Dependencies:
[init]   FLTK - 1.3.5
[init]   RtAudio - 5.1.0
[init]   RtMidi - 4.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.7.3
[midiMapConf::init] scanning midimaps directory '/home/mango/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
[1]    34060 segmentation fault (core dumped)  ./giada
```

**Comment by tomek-szczesny** [comment] 2020-07-25 13:10
Hi! Yes, I had a similar problem 2 days ago. Ultimately it turned out that my JACK server was not running properly in the first place.
I agree that more graceful handling of this trouble would be appreciated, however just to rule out a possibility that there is something else going on, @sezanzeb , could you please verify that your JACK server is working with some other software? Additionally, do you also happen to use PulseAudio and if so, how do you keep them both functional?
Cheers!

**Comment by sezanzeb** [comment] 2020-07-25 13:31
I'm using jack2 btw, if that matters. Yes it is working on other software.

To keep both pulseaudio and jack working at the same time, I'm using the pulseaudio bridge in cadence.

my knowledge of c++ is incredibly limited, so contributing is somewhat out of the question unfortunately.

**Comment by tomek-szczesny** [comment] 2020-07-25 17:49
Ha, now I see that I can reproduce a similar behavior by switching to ALSA, restarting, and trying to switch to Jack again. Upon clicking "Save" button, Giada crashes with similar error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)
Przerwane (zrzut pamięci)
```
Same happens when I try to switch to PulseAudio.
The huge number is 2^64-1, which might indicate a problem with type cast somewhere (it's an unsigned representation of signed integer "-1").

Oh well, now I broke my Giada and don't know how to make it work again.
Anyway I'm starting to think there is something wrong with config file handling.. 

And what do you know, I just skimmed through a _~/.giada/giada.conf_ file file searching for any "-1" entries, and indeed there are:
`(...),"channels_in":-1,"channels_out":-1,(...)`

I changed these to 0 et voila! It works! :)

@sezanzeb, could you try if this solution works for you? If so, that would be an easy fix I guess.

And no worries, I'm no C++ junkie either :D And a good feedback is also a good contribution.

**Comment by tomek-szczesny** [comment] 2020-07-26 10:15
@monocasual, I'd appreciate your input on whether it was normal for these settings to ever have a value of -1. I can try fixing it, I just need to know if something changed in Jack that started returning "-1" to some queries, or is it Giada that could handle such values in the past and all of the sudden stopped.

**Comment by sezanzeb** [comment] 2020-07-26 14:33
I just compiled it again and get the same error message as you

```
[init] Giada 0.16.4
[init] Build date: Jul 26 2020
[init] Dependencies:
[init]   FLTK - 1.3.5
[init]   RtAudio - 5.1.0
[init]   RtMidi - 4.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.28
[init]   JSON for modern C++ - 3.7.3
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '/home/mango/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)
```

no ~/.giada folder exists

the appimage behaves differently: I can set it to jack or alsa, but when I click the config button again, it crashes:

```
[init] Giada 0.16.3
[init] Build date: Jun 19 2020
[init] Dependencies:
[init]   FLTK - 1.3.5
[init]   RtAudio - 5.1.0
[init]   RtMidi - 4.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.25
[init]   JSON for modern C++ - 3.7.3
[init]   JUCE - 5.3.2
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '/home/mango/.giada/midimaps/'...
[midiMapConf::init] unable to scan midimaps directory!
[1]    6441 segmentation fault (core dumped)
```

still, no .giada folder exists.

I can set it to jack in the appimage, close it and it will generate ~/.giada/giada.conf with:

```
{"action_editor_grid_on":0,"action_editor_grid_val":0,"action_editor_h":480,"action_editor_w":640,"action_editor_x":640,"action_editor_y":300,"action_editor_zoom":100,"browser_h":480,"browser_last_path":"","browser_last_value":0,"browser_position":0,"browser_w":640,"browser_x":640,"browser_y":300,"buffer_size":1024,"channels_in":-1,"channels_out":-1,"chans_stop_on_seq_halt":false,"envelope_editor_h":40,"header":"GIADACFG","input_monitor_default_on":false,"last_midimap":"","limit_output":false,"log_mode":4,"main_window_h":510,"main_window_w":816,"main_window_x":552,"main_window_y":285,"midi_in":false,"midi_in_action_rec":0,"midi_in_beat_doble":0,"midi_in_beat_half":0,"midi_in_filter":-1,"midi_in_input_rec":0,"midi_in_metronome":0,"midi_in_rewind":0,"midi_in_start_stop":0,"midi_in_volume_in":0,"midi_in_volume_out":0,"midi_input_h":480,"midi_input_w":640,"midi_input_x":0,"midi_input_y":0,"midi_port_in":-1,"midi_port_out":-1,"midi_sync":0,"midi_system":2,"midi_tc_fps":25.0,"midimap_path":"","patches_path":"","piano_roll_h":422,"piano_roll_y":-1,"plugin_chooser_h":480,"plugin_chooser_w":640,"plugin_chooser_x":0,"plugin_chooser_y":0,"plugin_list_x":0,"plugin_list_y":0,"plugin_sort_method":0,"plugins_path":"","rec_trigger_level":-10.0,"rec_trigger_mode":0,"resample_quality":0,"sample_action_editor_h":40,"sample_editor_grid_on":0,"sample_editor_grid_val":0,"sample_editor_h":480,"sample_editor_w":640,"sample_editor_x":0,"sample_editor_y":0,"samplerate":44100,"samples_path":"","sound_device_in":-1,"sound_device_out":0,"sound_system":1,"treat_recs_as_loops":false,"velocity_editor_h":40}
```

I can set it to alsa, set the devices, close it, start it, set it to jack, close it, and am able to start it with jack running, and I get the following config:

```
{"action_editor_grid_on":0,"action_editor_grid_val":0,"action_editor_h":480,"action_editor_w":640,"action_editor_x":640,"action_editor_y":300,"action_editor_zoom":100,"browser_h":480,"browser_last_path":"","browser_last_value":0,"browser_position":0,"browser_w":640,"browser_x":640,"browser_y":300,"buffer_size":1024,"channels_in":0,"channels_out":0,"chans_stop_on_seq_halt":false,"envelope_editor_h":40,"header":"GIADACFG","input_monitor_default_on":false,"last_midimap":"","limit_output":false,"log_mode":4,"main_window_h":510,"main_window_w":816,"main_window_x":552,"main_window_y":285,"midi_in":false,"midi_in_action_rec":0,"midi_in_beat_doble":0,"midi_in_beat_half":0,"midi_in_filter":-1,"midi_in_input_rec":0,"midi_in_metronome":0,"midi_in_rewind":0,"midi_in_start_stop":0,"midi_in_volume_in":0,"midi_in_volume_out":0,"midi_input_h":480,"midi_input_w":640,"midi_input_x":0,"midi_input_y":0,"midi_port_in":-1,"midi_port_out":-1,"midi_sync":0,"midi_system":2,"midi_tc_fps":25.0,"midimap_path":"","patches_path":"","piano_roll_h":422,"piano_roll_y":-1,"plugin_chooser_h":480,"plugin_chooser_w":640,"plugin_chooser_x":0,"plugin_chooser_y":0,"plugin_list_x":0,"plugin_list_y":0,"plugin_sort_method":0,"plugins_path":"","rec_trigger_level":-10.0,"rec_trigger_mode":0,"resample_quality":0,"sample_action_editor_h":40,"sample_editor_grid_on":0,"sample_editor_grid_val":0,"sample_editor_h":480,"sample_editor_w":640,"sample_editor_x":0,"sample_editor_y":0,"samplerate":44100,"samples_path":"","sound_device_in":-1,"sound_device_out":0,"sound_system":1,"treat_recs_as_loops":false,"velocity_editor_h":40}
```

the only difference is `(...),"channels_in":-1,"channels_out":-1,(...)`

**Comment by tomek-szczesny** [comment] 2020-07-26 14:48
Thank you very much for your investigation!

I think that the message you got after the first crash (with no config file written) proves that there are no troubles writing a config file, as was previously suggested in #360. The message is the same as mine, when JACK within Giada was heavily misconfigured with negative numbers.
The thing is, I assume, Giada simply crashes before she's got a chance to write config file.

Walkaround with temporary ALSA setting seems to achieve only one goal, to get rid of "-1" values in config file.

Probably the best solution would be to limit output values from JACK to some sane range like (0-128) before storing them.

**Comment by keryell** [comment] 2020-07-27 08:30
> Probably the best solution would be to limit output values from JACK to some sane range like (0-128) before storing them.

Do you mean reading crappy value and trying to guess some unrelated value to be used instead?
If so, that sounds like a foot gun...

**Comment by tomek-szczesny** [comment] 2020-07-27 09:05
There's not much we can do about Jack returning "crappy value", except of an assumption that indeed a number of channels really shouldn't be negative. Nevertheless I'd be glad to see a better idea.

**Comment by sezanzeb** [comment] 2020-07-27 14:38
Checking if a value is valid and if not, using some default value sounds like a very reasonable thing to me. Unless the value is caused by some other bug in giada

**Comment by tomek-szczesny** [comment] 2020-07-27 15:12
Indeed. Can't say for sure, but it seems that Giada's config code is ancient and there were no recent changes in it. It is even hard to tell when the bug was made and where, because those who had their old config files were unaffected. And again, it **might** as well be a trouble with Jack changing its behavior [somewhere around version 1.9.12](https://repology.org/project/jack-audio-connection-kit/versions), because I remember installing old version of Giada from scratch on older version of Jack with no such problems.

**Comment by monocasual** [comment] 2020-07-28 17:55
@tomek-szczesny @sezanzeb did you find a way to reproduce the crash consistently? I can't, here on my machine. BTW channels count should always be >= 0. I guess those negative values crept in while counting channels from a non-existent/not-yet-running Jack.

**Comment by tomek-szczesny** [comment] 2020-07-28 21:26
Yes, I have just tried it again, and with already well configured Giada I take these steps:
Relevant portion of giada.conf: `"channels_in_count":1,"channels_in_start":0,"channels_out":0`
1. Run self-compiled Giada, Change sound system to Alsa, save, leave Giada
`,"channels_in_count":1,"channels_in_start":0,"channels_out":0,`
2. Run self-compiled Giada Again, switch sound system to Jack (or anything other than "none" for that matter), save, enjoy a crash:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)
Przerwane (zrzut pamięci)
```
After this crash, no changes were made in giada.conf, so step can be repeated with no success.
3. Run Giada in AppImage, change sound system to Jack, save changes and leave Giada.
`"channels_in":-1,"channels_out":0`
4. Run self-compiled Giada and finish setting up Jack to your liking.
`"channels_in_count":1,"channels_in_start":0,"channels_out":0`
5. Yay, Giada works.
6. Run AppImage and close it.
`,"channels_in":0,"channels_out":0,` and seems to work just fine
7. Run self-compiled Giada, get greeted by "your soundard isn't configured correctly", set output device and input device (in my case, again, input device was disabled), close Giada.
`,"channels_in_count":1,"channels_in_start":0,"channels_out":0,`
Steps 6-7 can be repeated independently.

So I guess I was not completely right. You actually can run any version of Giada with _channels_in_ set to "-1". If I manually edit _channels_out_ to "-1", self-compiled one won't run with memory violation error, and AppImage won't even show up. 

So, when do you get such a condition? When you do the following:
1b. Delete giada.conf
2b. Run self-compiled version and try setting up Jack, it will crash with an error like in 2.
3b. Run AppImage and choose Jack, exit Giada.
`"channels_in":-1,"channels_out":-1`
4b. Run AppImage again, it doesn't show up, neither does self-compiled version.
(Although I think I managed to run it at some point and it magically fixed both values. Nothing sure though)

OR

1c. Delete giada.conf
2c. Run AppImage and choose Jack, click "config" again.
Giada should disappear without writing config file. Steps can be repeated.

Now in order to recover, I have to manually set _channels_out_ to 0. 

So it is clear to me that config files of two versions are incompatible with each other, that's one thing.
Another wild guess is that upon creating json entries they default to -1 if not specified otherwise?

My self-compiled Giada is without VST support, that's the only difference I can think of.

As I said, I suspect that something also might have changed with Jack around 1.9.12, which I happen to have installed on my Ubuntu Studio Eoan.
```
mctom@Tomusiomat:~/git/giada$ jackd -V
jackdmp version 1.9.12 tmpdir /dev/shm protocol 8
```

**Comment by tomek-szczesny** [comment] 2020-07-29 23:49
Probably related to #330 and #318

**Comment by cuppajoeman** [comment] 2020-08-11 04:08
I'm also getting these problems with giada, for right now I'm just using the appimage version, but I'd like to get my compiled version to work at some point too!

**Comment by tomek-szczesny** [comment] 2020-08-11 07:20
@cuppajoeman you can use a workaround for now: in giada.conf file, change these values to 0 if any happens to be -1:
```
"channels_in":-1
"channels_out":-1
```

**Comment by tomek-szczesny** [comment] 2020-08-12 10:24
@cuppajoeman has described yet another case of the same problem: The same might happen when changing MIDI input settings. More in this forum post, including terminal output: https://www.giadamusic.com/forum/viewtopic.php?f=8&p=2589#p2583

**Comment by tomek-szczesny** [comment] 2020-09-24 22:58
Yup, so I looked around a bit and here's what I found.

There are actually two bugs lurking around here. One of them is saving a "-1", which crashes Giada's audio system at startup, and another one is, as I eventually found, [already fixed](https://github.com/monocasual/giada/commit/95520c00d49cc9f763d483a9eeaa2fef1851d161). The latter caused crashes when trying to save a new configuration with different audio (and possibly MIDI) engine.

The reason for crash #1 might be within RtAudio, which is accessed in [kernelAudio](https://github.com/monocasual/giada/blob/master/src/core/kernelAudio.cpp):

```
	RtAudio::StreamParameters outParams;
	RtAudio::StreamParameters inParams;

	outParams.deviceId     = conf::conf.soundDeviceOut == G_DEFAULT_SOUNDDEV_OUT ? getDefaultOut() : conf::conf.soundDeviceOut;
	outParams.nChannels    = G_MAX_IO_CHANS;
	outParams.firstChannel = conf::conf.channelsOut * G_MAX_IO_CHANS; // chan 0=0, 1=2, 2=4, ...
```

All three StreamParameters are of unsigned int type, and assigning negative number to any of them sounds like trouble. Earlier I found out that negative value of _channels_out_ config parameter, crashes Giada at startup. (You can try this at home!)

The problem, I believe, lies [here](https://github.com/monocasual/giada/blob/56cff0d62a319e3b1b2711beb4d8d2f7094eb006/src/gui/elems/config/tabAudio.cpp#L517), when a value of a deactivated geChoice object is stored - and I think it's -1.

But my girlfriend surely isn't happy that I'm not in bed yet, so I'll test it some other time..

**Comment by tomek-szczesny** [comment] 2020-09-25 10:33
I checked the latest master branch and it seems that this problem is fully fixed, no further changes needed. I think it can be marked as solved and closed.

**Comment by keryell** [comment] 2020-09-25 15:33
Perhaps it is a good opportunity to remove most of the unsigned usage in the code... This is a sad story in C++ inherited from bad choices in C which still triggers a lot of discussions inside the ISO C++ committee, leading for example to a new `std::ssize`...

About your girlfriend, you could watch some C++20 tutorials together, for example from the recent https://cppcon.org/ ? ;-)

**Comment by monocasual** [comment] 2020-09-26 13:17
> I checked the latest master branch and it seems that this problem is fully fixed, no further changes needed. I think it can be marked as solved and closed.

@tomek-szczesny  Yeah we touched that part of I/O code in the latest commits, so the bug might have been silently fixed. Good luck with the C++20 tutorials together :stuck_out_tongue: 

> Perhaps it is a good opportunity to remove most of the unsigned usage in the code... 

@keryell That would be a nice thing to have. Please feel free to open an issue to keep track of it.

**Comment by tomek-szczesny** [comment] 2020-11-19 08:35
It seems that version 0.17 [is still affected](https://www.giadamusic.com/forum/viewtopic.php?f=2&t=1592&p=2632#p2629) with this bug. :(

**Comment by dvzrv** [comment] 2020-11-20 18:24
I can confirm that 0.17.0 is broken as well. I have tried your suggested workarounds of resetting some of the `-1` values to `0`. Eventually giada detects my firewire interface in the config as an output device, but as soon as I want to set the input device to it as well, it crashes.

```
           PID: 2510999 (giada)
           UID: 1000 (dave)
           GID: 1000 (dave)
        Signal: 6 (ABRT)
     Timestamp: Fri 2020-11-20 19:22:11 CET (2min 14s ago)
  Command Line: giada
    Executable: /usr/bin/giada
 Control Group: /user.slice/user-1000.slice/user@1000.service/tmux.service
          Unit: user@1000.service
     User Unit: tmux.service
         Slice: user-1000.slice
     Owner UID: 1000 (dave)
       Boot ID: 4a120176b55b4296b51f536e33cb486c
    Machine ID: a5640b7a4f7946aa8d2d075962e96526
      Hostname: hmbx
       Storage: /var/lib/systemd/coredump/core.giada.1000.4a120176b55b4296b51f536e33cb486c.2510999.1605896531000000.zst
       Message: Process 2510999 (giada) of user 1000 dumped core.
                
                Stack trace of thread 2510999:
                #0  0x000069da6f7e8615 raise (libc.so.6 + 0x3d615)
                #1  0x000069da6f7d1862 abort (libc.so.6 + 0x26862)
                #2  0x000069da6fb6c86a _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9686a)
                #3  0x000069da6fb78d9a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa2d9a)
                #4  0x000069da6fb78e07 _ZSt9terminatev (libstdc++.so.6 + 0xa2e07)
                #5  0x000069da6fb790ae __cxa_throw (libstdc++.so.6 + 0xa30ae)
                #6  0x000069da6fb6f5ed _ZSt24__throw_out_of_range_fmtPKcz (libstdc++.so.6 + 0x995ed)
                #7  0x0000000bf1196344 n/a (giada + 0x93344)
                #8  0x0000000bf1191b7e n/a (giada + 0x8eb7e)
                #9  0x0000000bf1172671 n/a (giada + 0x6f671)
                #10 0x000069da701e9542 _ZN9Fl_Widget11do_callbackEPS_Pv (libfltk.so.1.3 + 0xaa542)
                #11 0x000069da70195e81 _ZN9Fl_Button6handleEi (libfltk.so.1.3 + 0x56e81)
                #12 0x000069da7018d753 n/a (libfltk.so.1.3 + 0x4e753)
                #13 0x000069da7018f4fe _ZN2Fl7handle_EiP9Fl_Window (libfltk.so.1.3 + 0x504fe)
                #14 0x000069da701f0ae4 _Z9fl_handleRK7_XEvent (libfltk.so.1.3 + 0xb1ae4)
                #15 0x000069da701f2406 n/a (libfltk.so.1.3 + 0xb3406)
                #16 0x000069da701f2787 _Z7fl_waitd (libfltk.so.1.3 + 0xb3787)
                #17 0x000069da7018ef8c _ZN2Fl4waitEd (libfltk.so.1.3 + 0x4ff8c)
                #18 0x000069da7018f042 _ZN2Fl3runEv (libfltk.so.1.3 + 0x50042)
                #19 0x0000000bf112909e main (giada + 0x2609e)
                #20 0x000069da6f7d3152 __libc_start_main (libc.so.6 + 0x28152)
                #21 0x0000000bf11290de n/a (giada + 0x260de)
                
                Stack trace of thread 2511027:
                #0  0x000069da6f8a5d5d syscall (libc.so.6 + 0xfad5d)
                #1  0x000069da6ffca7db n/a (libjack.so.0 + 0x327db)
                #2  0x000069da6ffacfa5 n/a (libjack.so.0 + 0x14fa5)
                #3  0x000069da6ffac177 n/a (libjack.so.0 + 0x14177)
                #4  0x000069da6ffabef8 n/a (libjack.so.0 + 0x13ef8)
                #5  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #6  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #7  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 2511026:
                #0  0x000069da6fea800c read (libpthread.so.0 + 0x1300c)
                #1  0x000069da6ffc9b2f n/a (libjack.so.0 + 0x31b2f)
                #2  0x000069da6ffce73d n/a (libjack.so.0 + 0x3673d)
                #3  0x000069da6ffce572 n/a (libjack.so.0 + 0x36572)
                #4  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #5  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 2511025:
                #0  0x000069da6f8a5d5d syscall (libc.so.6 + 0xfad5d)
                #1  0x000069da6ffca7db n/a (libjack.so.0 + 0x327db)
                #2  0x000069da6ffacfa5 n/a (libjack.so.0 + 0x14fa5)
                #3  0x000069da6ffac177 n/a (libjack.so.0 + 0x14177)
                #4  0x000069da6ffabef8 n/a (libjack.so.0 + 0x13ef8)
                #5  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #6  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #7  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 2511023:
                #0  0x000069da6f8a5d5d syscall (libc.so.6 + 0xfad5d)
                #1  0x000069da6ffca7db n/a (libjack.so.0 + 0x327db)
                #2  0x000069da6ffacfa5 n/a (libjack.so.0 + 0x14fa5)
                #3  0x000069da6ffac177 n/a (libjack.so.0 + 0x14177)
                #4  0x000069da6ffabef8 n/a (libjack.so.0 + 0x13ef8)
                #5  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #6  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #7  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 2511024:
                #0  0x000069da6fea800c read (libpthread.so.0 + 0x1300c)
                #1  0x000069da6ffc9b2f n/a (libjack.so.0 + 0x31b2f)
                #2  0x000069da6ffce73d n/a (libjack.so.0 + 0x3673d)
                #3  0x000069da6ffce572 n/a (libjack.so.0 + 0x36572)
                #4  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #5  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 2511021:
                #0  0x000069da6fea46a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x000069da6ffc93c0 n/a (libjack.so.0 + 0x313c0)
                #2  0x000069da6ffbd456 n/a (libjack.so.0 + 0x25456)
                #3  0x000069da6ffc88ed n/a (libjack.so.0 + 0x308ed)
                #4  0x000069da6fe9e3e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x000069da6f8ab293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thre
```

**Comment by dvzrv** [comment] 2020-11-20 18:29
Weirdly enough giada is actually connected to the first input channel of my interface (although in the config no interface is selected for the input) and connects two output channels to the 5th and 6th output of my interface (although the Output channels are set to `None` and I can't change that either apparently).

This config somehow works:
```
{
  "action_editor_grid_on": 0,
  "action_editor_grid_val": 0,
  "action_editor_h": 480,
  "action_editor_w": 640,
  "action_editor_x": 280,
  "action_editor_y": 720,
  "action_editor_zoom": 100,
  "browser_h": 480,
  "browser_last_path": "",
  "browser_last_value": 0,
  "browser_position": 0,
  "browser_w": 640,
  "browser_x": 280,
  "browser_y": 720,
  "buffer_size": 256,
  "channels_in_count": 1,
  "channels_in_start": -1,
  "channels_out": 0,
  "chans_stop_on_seq_halt": false,
  "envelope_editor_h": 40,
  "header": "GIADACFG",
  "input_monitor_default_on": false,
  "last_midimap": "",
  "limit_output": false,
  "log_mode": 4,
  "main_window_h": 1315,
  "main_window_w": 1196,
  "main_window_x": 2402,
  "main_window_y": 33,
  "midi_in": false,
  "midi_in_action_rec": 0,
  "midi_in_beat_doble": 0,
  "midi_in_beat_half": 0,
  "midi_in_filter": 0,
  "midi_in_input_rec": 0,
  "midi_in_metronome": 0,
  "midi_in_rewind": 0,
  "midi_in_start_stop": 0,
  "midi_in_volume_in": 0,
  "midi_in_volume_out": 0,
  "midi_input_h": 480,
  "midi_input_w": 640,
  "midi_input_x": 0,
  "midi_input_y": 0,
  "midi_port_in": -1,
  "midi_port_out": -1,
  "midi_sync": 0,
  "midi_system": 3,
  "midi_tc_fps": 25,
  "midimap_path": "",
  "overdub_protection_default_on": false,
  "patches_path": "",
  "piano_roll_h": 422,
  "piano_roll_y": -1,
  "plugin_list_x": 0,
  "plugin_list_y": 0,
  "plugins_path": "",
  "rec_trigger_level": -10,
  "rec_trigger_mode": 0,
  "resample_quality": 0,
  "sample_action_editor_h": 40,
  "sample_editor_grid_on": 0,
  "sample_editor_grid_val": 0,
  "sample_editor_h": 480,
  "sample_editor_w": 640,
  "sample_editor_x": 0,
  "sample_editor_y": 0,
  "samplerate": 48000,
  "samples_path": "",
  "sound_device_in": -1,
  "sound_device_out": 0,
  "sound_system": 1,
  "treat_recs_as_loops": false,
  "velocity_editor_h": 40
}
```

**Comment by monocasual** [comment] 2020-11-20 20:37
Finally I was able to reproduce the crash:

1. delete the `giada.conf` file (somewhere in your system, e.g. on Linux `~/.giada/giada.conf`;
1. start Giada 
1. set JACK in the configuration window;
1. close Giada and restart;
1. segfault!

Investigating...

**Comment by monocasual** [comment] 2020-11-20 21:04
Should be fixed in 37f0440b3d65e5c232e0f8be6be041a7b9282faf . The `channelOut` value in the json object was incorrectly set to `-1` during save.

**Comment by tomek-szczesny** [comment] 2020-11-21 10:57
This bug has caused a lot of confusion, because it's not just a matter to get a fixed version of Giada to sort out the problem, when giada.conf is already broken.

Are we able to catch a segfault globally somehow? It would be nice if Giada deleted/renamed its config file if it was abnormally terminated.

**Comment by monocasual** [comment] 2020-11-22 16:30
Pushed another commit 3b1592a6bd6dd994e95eecd260fe2cf7c8e0e379 that sanitizes data in the configuration file. 

> Are we able to catch a segfault globally somehow? It would be nice if Giada deleted/renamed its config file if it was abnormally terminated.

Not yet, might be worth adding in the future (also for plug-ins).

**Comment by tomek-szczesny** [comment] 2020-11-22 21:11
> > Are we able to catch a segfault globally somehow? It would be nice if Giada deleted/renamed its config file if it was abnormally terminated.
> 
> Not yet, might be worth adding in the future (also for plug-ins).

What could be done is simply creating a lock file that is deleted during normal exit. If a lock file is present at startup, that means something went wrong last time. 
Unless we want to let users use multiple instances of Giada?

**Comment by gvnnz** [comment] 2020-12-26 17:25
Closing as fixed in master branch. Please reopen if the error persists.

**Closed by gvnnz** 2020-12-26 17:25 UTC
Labels: bug
