### ISSUE TITLE
Can't clear keyboard bindings

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#708] opened 2024-10-28 17:12 UTC
**Environment**
- OS: all
- Giada version: 1.1.0

**Describe the bug**
Can't clear keyboard bindings previously assigned.

**Comment by gvnnz** [comment] 2024-12-06 21:13
Can't reproduce, probably related to #717. Closing

**Closed by gvnnz** 2024-12-06 21:13 UTC
Labels: bug

**Comment by gvnnz** [comment] 2024-12-07 17:04
Actually fixed in https://github.com/monocasual/giada/commit/d12c15ac25410c8f8516e2585332717ff1531bb6.
