### ISSUE TITLE
Segfault on quit on OS X El Capitan

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#79] opened 2016-06-02 08:58 UTC
When I quit giada with command+q key input, This binary shows these error messages.
-- from here --
**\* Leaked objects detected: 1 instance(s) of class MessageManager
JUCE Assertion failure in juce_LeakedObjectDetector.h:95
Segmentation fault
logout

**Comment by gvnnz** [comment] 2023-12-17 14:05
Can't reproduce it, too old. Closing.

**Closed by gvnnz** 2023-12-17 14:05 UTC
Labels: bug, To be confirmed
