### ISSUE TITLE
Crash when using MIDI input to start global input recording

### ISSUE THREAD

**Issue by dorgnarg** [monocasual/giada#181] opened 2018-05-01 00:38 UTC
If I set input recording to a MIDI signal (of any kind that I've been able to figure out), and then I try to use that note to start recording samples, if there's no armed channel, or if the armed channel already has a take on it, Giada crashes. If I use a mouse to click the record button, it'll work fine if there's an armed channel, or it'll give a pop-up if there isn't an armed channel, but there's never an issue with crashing (at least, as many times as I've tried testing it). I'm running Fedora 27 on a laptop, kernel version 4.14.13-300.fc27.x86_64, but this also happens on my Raspberry Pi, which is using Raspbian Stretch (I don't have access to it right at this moment so I'm not sure the kernel version). All of this is using Giada version 0.15.0.

I've tried this with both note signals and program change signals, with both physical and virtual midi instruments, with the "no note off" option in both positions, with no noticeable differences.

Here's the output from the last time I tried with debugging enabled:
```
[init] Giada 0.15.0 - Mon Apr 30 17:34:14 2018
[init] configuration file ready
[init] scanning midimaps directory...
[init] unable to scan midimaps directory!
[read] midimap not specified, nothing to do
[init_prepareMidiMap] MIDI map read failed!
[KA] using system 0x1
[KA] Opening devices 0 (out), 0 (in), f=44100...
[KA] 2 device(s) found
  0) system
  1) jack-keyboard
[KA] JACK in use, freq = 44100
[Mixer::init] buffers ready - framesInSeq=88200, framesInBuffer=128
[KM] using system 0x3
[KM] 1 output MIDI ports found
  0) jack-keyboard:midi_in
[KM] 1 input MIDI ports found
  0) jack-keyboard:midi_out
[KM] MIDI in port 0 open
[geKeyboard::__cb_addColumn] new column added (index=0, w=380), total count=1, addColumn(x)=404
[geKeyboard::__cb_addColumn] new column added (index=1, w=380), total count=2, addColumn(x)=800
[geKeyboard::__cb_addColumn] new column added (index=2, w=380), total count=3, addColumn(x)=1196
[geKeyboard::__cb_addColumn] new column added (index=3, w=380), total count=4, addColumn(x)=1592
[geKeyboard::__cb_addColumn] new column added (index=4, w=380), total count=5, addColumn(x)=1988
[geKeyboard::__cb_addColumn] new column added (index=5, w=380), total count=6, addColumn(x)=2384
[KA] latency = 384
[midiDispatcher] MIDI received - 0x90154000 (chan 0)
[gdMidiGrabber] MIDI learn done - message=0x90150000
[midiDispatcher] MIDI received - 0x80154000 (chan 0)
[geColumn::__cb_addChannel] m_index = 0
[addChannel] channel index=0 added, type=1, total=1
[geKeyboard::addChannel] add to column with index=0, size=20
[midiDispatcher] MIDI received - 0x90154000 (chan 0)
  >>> inputRec (master) (pure=0x90150000)
[waveManager::createEmpty] new empty Wave created, 88200 frames
[startInputRec] start input recs using chan 0 with size 88200 on frame=0
[midiDispatcher] MIDI received - 0x80154000 (chan 0)
[midiDispatcher] MIDI received - 0x90154000 (chan 0)
  >>> inputRec (master) (pure=0x90150000)
[mh] stop input recs
[midiDispatcher] MIDI received - 0x80154000 (chan 0)
[midiDispatcher] MIDI received - 0x90154000 (chan 0)
  >>> inputRec (master) (pure=0x90150000)
X I/O error
```

**Comment by tomek-szczesny** [comment] 2018-10-28 10:17
It happened to me once and I also got "I/O Error" notice. I did something wrong to the debugger and lost the stack info, but I'll take a closer look at this issue, since I play with MIDI support a lot lately.

**Comment by tomek-szczesny** [comment] 2018-10-29 20:10
Okay, now I reproduce this error by merely assigning any Launchpad key to "Input Rec" function, and clicking it 2-3 times, without even any channels created. As I press the button I can see the expected message window, and on the last attempt, program crashes. There is no pattern to how many times the button must be pressed before the crash, it usually took 1-4 presses.
As far as I can tell the crash occurs because of the "gdAlert" window popping up.
My guess is that the problem lies within "gu_setFavicon", in linux ifdef, because all reported target systems were linux so far, and also X is somehow directly called in there. And "X I/O Error" is the X complaining. And see the debug session below.

So I guess I won't be digging much deeper into this, that's way beyond my capabilities for now. Harder than playing with midi support.

Here's one lucky debug session:

```
Thread 17 "giada" hit Breakpoint 4, giada::c::io::startInputRec (gui=false)
    at src/glue/io.cpp:168
168	{
(gdb) n
172			return false;
(gdb) n
168	{
(gdb) n
171		if (kernelAudio::getStatus() == false)
(gdb) n
174		if (!mh::startInputRec()) {
(gdb) n

Thread 17 "giada" hit Breakpoint 4, giada::m::mh::startInputRec ()
    at src/core/mixerHandler.cpp:287
287	{
(gdb) n
290		for (Channel* ch : mixer::channels) {
(gdb) n
288		int channelsReady = 0;
(gdb) n
290		for (Channel* ch : mixer::channels) {
(gdb) n
317			return false;
(gdb) n
320	}
(gdb) n
giada::c::io::startInputRec (gui=<optimized out>) at src/glue/io.cpp:175
175			Fl::lock();
(gdb) n
176			G_MainWin->mainTransport->updateRecInput(0);  // set it off, anyway
(gdb) n
177			Fl::unlock();
(gdb) n
197	}
(gdb) n
giada::c::io::startStopInputRec (gui=<optimized out>) at src/glue/io.cpp:160
160			gdAlert("No channels armed/available for audio recording.");
(gdb) n
161	}
(gdb) n
160			gdAlert("No channels armed/available for audio recording.");
(gdb) n
gdAlert (c=0x5555555c9528 "No channels armed/available for audio recording.")
    at src/gui/dialogs/gd_warnings.cpp:39
39	{
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
43				300, 90, "Alert");
(gdb) n
42				(Fl::h() / 2) - 47,
(gdb) n
41				(Fl::w() / 2) - 150,
(gdb) n
43				300, 90, "Alert");
(gdb) n
44		modal->set_modal();
(gdb) n
45		modal->begin();
(gdb) n
46			geBox *box = new geBox(10, 10, 280, 40, c);
(gdb) n
47			geButton *b = new geButton(210, 60, 80, 20, "Close");
(gdb) n
48		modal->end();
(gdb) n
50		b->callback(__cb_window_closer, (void *)modal);
(gdb) n
52		gu_setFavicon(modal);
(gdb) n
49		box->labelsize(G_GUI_FONT_SIZE_BASE);
(gdb) n
51		b->shortcut(FL_Enter);
(gdb) n
50		b->callback(__cb_window_closer, (void *)modal);
(gdb) n
52		gu_setFavicon(modal);
(gdb) n
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
giada: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```

**Comment by tomek-szczesny** [comment] 2018-10-30 15:14
I confirmed that commenting out _gu_setFavicon(modal);_ from _gd_warnings.cpp_ solves the problem. No crashes whatsoever. The favicon routine for Linux must be changed then.

**Comment by monocasual** [comment] 2018-10-31 08:59
@tomek-szczesny interesting. I wonder what's wrong with the favicon code in there. I am unable to reproduce the issue right now on my Linux machine.

Adding my 2 cents: as @tblrchstr knows, Giada currently takes care of concurrency in a sluggish way, especially the core -> UI part. We (well, @tblrchstr) are working on this: maybe those X function calls in `gu_setFavicon` are clashing with some other bits in another thread - I'm just guessing of course.

@tomek-szczesny the latest commits in `master` branch already contain some improvements on this. Feel free to check them out to see if the issue persists...

**Comment by tomek-szczesny** [comment] 2018-10-31 14:06
According to what I've read, X doesn't like getting requests from various threads. This is not an issue when there's a middleman (fltk in this case). This is why it is strongly suggested to avoid talking to X directly.

I think the reason this bug occurs only when using MIDI controller is that a different (non-UI) thread is handling it. Not sure why it never happens on your machine, but I'll be happy to test all possible solutions.

I conducted my tests on the most recent master branch, so the problem persists. I see that direct X calls over there are merely for transforming an ascii art into a bitmap, and I hope this could be done without bugging old X. I'll see what I can do.

**Comment by tomek-szczesny** [comment] 2018-11-10 20:11
http://www.fltk.org/doc-1.3/osissues.html#osissues_x_icon

I see that the troublesome code has been adapted from here. I find it rather peculiar that the very same FLTK programming manual regards the ft_window::icon() method as deprecated as of version 1.3.3.

My suggestion for a workaround is to try and use default_icon method on main window instead. This way, any new windows should inherit an icon. I tried, but this seems to be too hard for me.

**Comment by monocasual** [comment] 2020-07-18 14:02
Is this still an issue in Giada 0.16.x ? Can't reproduce here.

**Comment by monocasual** [comment] 2020-09-05 07:54
No feedback, closing for now. Please feel free to reopen it if the bug is still present.

**Closed by monocasual** 2020-09-05 07:54 UTC
Labels: To be confirmed, bug
