### ISSUE TITLE
Giaga 0.17.0 win 64 download missing .dll file

### ISSUE THREAD

**Issue by drageset** [monocasual/giada#439] opened 2020-12-04 14:03 UTC
**Environment**
- OS: Windows 10 Home 64 bit, Version 1909, OS Build 18363.1198
- Giada version: 0.17.0

**Description**
When I attempt to start Giada for the first time, I get an error message indicating a dll is missing.

**To Reproduce**
1. Go to https://www.giadamusic.com/download, and download the Win x64 edition
2. Unpack the zip, and run the giada.exe

**Expected behavior**
The app starts

**Screenshots**
![bug screen cap](https://user-images.githubusercontent.com/28501510/101172641-b6a56980-3641-11eb-9ee4-6331e0d61eec.PNG)

**Comment by tomek-szczesny** [comment] 2020-12-04 15:39
Hi! Thanks for your effort, but this has already been reported. So, it's a duplicate of #420.

**Comment by drageset** [comment] 2020-12-04 18:37
Ah, ok! Thanks @tomek-szczesny

**Comment by gvnnz** [comment] 2020-12-07 18:05
@drageset please give the experimental build in #420 a try. Thanks!

**Closed by gvnnz** 2020-12-07 18:05 UTC
